# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Spreadsheet-WriteExcel-Simple-Tabs
version:      0.03
version_from: lib/Spreadsheet/WriteExcel/Simple/Tabs.pm
installdirs:  site
requires:
    IO::Scalar:                    0
    Spreadsheet::WriteExcel:       0
    strict:                        0
    Test::Simple:                  0.44
    warnings:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
